name: build

on:
  push:
    branches: master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v5

      - name: Validate Gradle Wrapper
        uses: gradle/actions/wrapper-validation@v5

      - name: Setup JDK 17
        uses: actions/setup-java@v5
        with:
          distribution: zulu
          java-version: 17

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5

      - name: Grant gradle executable permission
        run: chmod +x gradlew

      - name: Run Local Unit Tests
        run: ./gradlew testdebug
